DROP DATABASE IF EXISTS "schema386";
CREATE DATABASE "schema386";
USE "schema386";
CREATE TABLE "bpm_variable_dict" (
	"variable_id" BIGINT,
	"process_id" BIGINT,
	"tenant_id" VARCHAR,
	"data_key" VARCHAR,
	"data_name" VARCHAR,
	"data_type" VARCHAR,
	"check_rule" VARCHAR,
	"special_value" VARCHAR,
	"special_value2" VARCHAR,
	"process_data" TINYINT,
	"sort" SMALLINT,
	"allow_edit_node_id" VARCHAR,
	"hidden_node_id" VARCHAR,
	"required_node_id" VARCHAR,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("variable_id")
);

CREATE TABLE "bpm_user_task" (
	"task_id" BIGINT,
	"act_task_id" VARCHAR,
	"apply_id" BIGINT,
	"process_id" BIGINT,
	"proc_inst_id" VARCHAR,
	"task_type" VARCHAR,
	"tenant_id" VARCHAR,
	"task_name" VARCHAR,
	"task_node_code" VARCHAR,
	"parent_task_id" BIGINT,
	"task_status" TINYINT,
	"role_group_code" BIGINT,
	"role_code" BIGINT,
	"role_name" VARCHAR,
	"task_owner_user_id" BIGINT,
	"task_owner_real_name" VARCHAR,
	"task_assignee_user_id" BIGINT,
	"task_assignee_real_name" VARCHAR,
	"task_priority" TINYINT,
	"form_key" VARCHAR,
	"form_type" TINYINT,
	"claim_time" DATETIME,
	"due_time" DATETIME,
	"approve_time" DATETIME,
	"system" VARCHAR,
	"platform" VARCHAR,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("task_id")
);

CREATE TABLE "bpm_user_role" (
	"id" BIGINT,
	"user_id" BIGINT,
	"role_id" BIGINT,
	"alias_name" VARCHAR,
	"tenant_id" VARCHAR,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("id")
);

CREATE TABLE "bpm_user" (
	"id" VARCHAR,
	"user_id" BIGINT,
	"user_name" VARCHAR,
	"real_name" VARCHAR,
	"email" VARCHAR,
	"phone" VARCHAR,
	"position_code" VARCHAR,
	"position_name" VARCHAR,
	"gender" TINYINT,
	"avatar" VARCHAR,
	"birth_date" DATETIME,
	"company_id" BIGINT,
	"dept_id" BIGINT,
	"tenant_id" VARCHAR,
	"password" VARCHAR,
	"entry_time" DATETIME,
	"leave_time" DATETIME,
	"hire_status" TINYINT,
	"source" VARCHAR,
	"lock_status" TINYINT,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("id")
);

CREATE TABLE "bpm_tenant" (
	"tenant_id" VARCHAR,
	"tenant_name" VARCHAR,
	"effective_start_time" DATETIME,
	"effective_end_time" DATETIME,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("tenant_id")
);

CREATE TABLE "bpm_sql_log" (
	"log_id" BIGINT,
	"log_type" VARCHAR,
	"log_sql" TEXT,
	"spend_time" BIGINT,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("log_id")
);

CREATE TABLE "bpm_role_group_to_role" (
	"id" BIGINT,
	"role_group_id" BIGINT,
	"role_id" BIGINT,
	"tenant_id" VARCHAR,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("id")
);

CREATE TABLE "bpm_role_group" (
	"role_group_id" BIGINT,
	"role_group_code" VARCHAR,
	"role_group_name" VARCHAR,
	"role_group_abbr" VARCHAR,
	"business_line" VARCHAR,
	"role_group_level" TINYINT,
	"role_group_type" TINYINT,
	"tenant_id" VARCHAR,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("role_group_id")
);

CREATE TABLE "bpm_role" (
	"role_id" BIGINT,
	"role_code" VARCHAR,
	"role_name" VARCHAR,
	"role_level" TINYINT,
	"role_abbr" VARCHAR,
	"role_alias_name" VARCHAR,
	"tenant_id" VARCHAR,
	"company_id" BIGINT,
	"dept_id" BIGINT,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("role_id")
);

CREATE TABLE "bpm_process_rule" (
	"rule_id" CHAR,
	"rule_name" VARCHAR,
	"rule_code" VARCHAR,
	"rule_type" SMALLINT,
	"tenant_id" VARCHAR,
	"process_id" INT,
	"role_group_id" INT,
	"role_id" INT,
	"user_id" INT,
	"rule_expression" VARCHAR,
	"rule_action" VARCHAR,
	"rule_users" VARCHAR,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" INT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("rule_id")
);

CREATE TABLE "bpm_process_detail" (
	"process_detail_id" BIGINT,
	"tenant_id" VARCHAR,
	"process_id" BIGINT,
	"process_xml" MEDIUMTEXT,
	"definition_id" VARCHAR,
	"apply_title_rule" VARCHAR,
	"apply_due_date" DATETIME,
	"auto_complete_first_node" TINYINT,
	"publish_status" TINYINT,
	"main_version" TINYINT,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("process_detail_id")
);

CREATE TABLE "bpm_process" (
	"process_id" BIGINT,
	"process_key" VARCHAR,
	"process_name" VARCHAR,
	"process_menu_id" BIGINT,
	"process_abbr" VARCHAR,
	"process_type" TINYINT,
	"company_id" BIGINT,
	"company_code" VARCHAR,
	"sort" SMALLINT,
	"tenant_id" VARCHAR,
	"process_detail_id" BIGINT,
	"process_status" TINYINT,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("process_id")
);

CREATE TABLE "bpm_operator_log" (
	"log_id" BIGINT,
	"user_id" BIGINT,
	"nickname" VARCHAR,
	"trace_id" VARCHAR,
	"business_type" VARCHAR,
	"module_name" VARCHAR,
	"class_name" VARCHAR,
	"method_name" VARCHAR,
	"request_method" VARCHAR,
	"ip_address" VARCHAR,
	"detail_address" VARCHAR,
	"browser" VARCHAR,
	"os" VARCHAR,
	"operator_type" TINYINT,
	"param" VARCHAR,
	"code" SMALLINT,
	"message" VARCHAR,
	"data" TEXT,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("log_id")
);

CREATE TABLE "bpm_node_user" (
	"node_user_id" BIGINT,
	"apply_id" BIGINT,
	"proc_inst_id" VARCHAR,
	"process_id" BIGINT,
	"process_key" VARCHAR,
	"node_id" VARCHAR,
	"node_name" VARCHAR,
	"parent_node_id" VARCHAR,
	"parent_node_name" VARCHAR,
	"definition_id" VARCHAR,
	"tenant_id" VARCHAR,
	"assignee_user_id_list" VARCHAR,
	"assignee_user_name_list" VARCHAR,
	"skip" TINYINT,
	"default_set_admin" TINYINT,
	"error" TINYINT,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("node_user_id")
);

CREATE TABLE "bpm_node" (
	"id" BIGINT,
	"node_id" VARCHAR,
	"node_name" VARCHAR,
	"definition_id" VARCHAR,
	"process_id" BIGINT,
	"process_key" VARCHAR,
	"tenant_id" VARCHAR,
	"node_type" VARCHAR,
	"task_type" VARCHAR,
	"priority" SMALLINT,
	"form_key" VARCHAR,
	"form_name" VARCHAR,
	"form_type" TINYINT,
	"user_id_list" VARCHAR,
	"user_name_list" VARCHAR,
	"role_group_code" VARCHAR,
	"role_group_name" VARCHAR,
	"role_code" VARCHAR,
	"role_name" VARCHAR,
	"find_user_type" TINYINT,
	"combine_type" TINYINT,
	"assignee_field" VARCHAR,
	"select_path" TINYINT,
	"handler_strategy" VARCHAR,
	"relation_node_id" VARCHAR,
	"action_list" VARCHAR,
	"skip_expression" VARCHAR,
	"expression" VARCHAR,
	"source_ref" VARCHAR,
	"target_ref" VARCHAR,
	"sequential" VARCHAR,
	"proportion" VARCHAR,
	"custom_sql" TEXT,
	"custom_data" VARCHAR,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("id")
);

CREATE TABLE "bpm_message_white_list" (
	"white_id" VARCHAR,
	"tenant_id" VARCHAR,
	"process_id" INT,
	"white_type_code" VARCHAR,
	"white_list" VARCHAR,
	"order" SMALLINT,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" INT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("white_id")
);

CREATE TABLE "bpm_message_content" (
	"content_id" BIGINT,
	"content_code" VARCHAR,
	"tenant_id" VARCHAR,
	"message_title" VARCHAR,
	"message_content" TEXT,
	"message_type_code" VARCHAR,
	"message_system_code" VARCHAR,
	"message_platform" VARCHAR,
	"process_id" INT,
	"default_falg" TINYINT,
	"event_codes" VARCHAR,
	"event_names" VARCHAR,
	"order" SMALLINT,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" INT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("content_id")
);

CREATE TABLE "bpm_menu" (
	"menu_id" BIGINT,
	"menu_code" VARCHAR,
	"menu_name" VARCHAR,
	"menu_icon" VARCHAR,
	"menu_url" VARCHAR,
	"menu_type" VARCHAR,
	"meta" VARCHAR,
	"always_show" TINYINT,
	"parent_id" BIGINT,
	"tenant_id" VARCHAR,
	"component" VARCHAR,
	"hidden" TINYINT,
	"sort" SMALLINT,
	"redirect" VARCHAR,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("menu_id")
);

CREATE TABLE "bpm_history" (
	"history_id" BIGINT,
	"apply_id" BIGINT,
	"task_id" BIGINT,
	"task_name" VARCHAR,
	"tenant_id" VARCHAR,
	"system" VARCHAR,
	"platform" VARCHAR,
	"approve_action_code" VARCHAR,
	"approve_action_name" VARCHAR,
	"approve_opinion" VARCHAR,
	"approve_user_id" BIGINT,
	"approve_real_name" VARCHAR,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("history_id")
);

CREATE TABLE "bpm_form_data_1" (
	"data_id" BIGINT,
	"data_key" VARCHAR,
	"data_name" VARCHAR,
	"string_value" VARCHAR,
	"boolean_value" TINYINT,
	"number_value" DECIMAL,
	"number_format" VARCHAR,
	"date_value" DATETIME,
	"date_pattern" VARCHAR,
	"select_value" VARCHAR,
	"select_item" VARCHAR,
	"text_value" LONGTEXT,
	"data_type" VARCHAR,
	"form_id" BIGINT,
	"form_key" VARCHAR,
	"tenant_id" VARCHAR,
	"process_id" BIGINT,
	"apply_id" BIGINT,
	"proc_inst_id" VARCHAR,
	"task_id" BIGINT,
	"valid_state" TINYINT,
	"create_time" DATETIME,
	"update_time" DATETIME,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	 PRIMARY KEY ("data_id")
);

CREATE TABLE "bpm_form_data_0" (
	"data_id" BIGINT,
	"data_key" VARCHAR,
	"data_name" VARCHAR,
	"string_value" VARCHAR,
	"boolean_value" TINYINT,
	"number_value" DECIMAL,
	"number_format" VARCHAR,
	"date_value" DATETIME,
	"date_pattern" VARCHAR,
	"select_value" VARCHAR,
	"select_item" VARCHAR,
	"text_value" LONGTEXT,
	"data_type" VARCHAR,
	"form_id" BIGINT,
	"form_key" VARCHAR,
	"tenant_id" VARCHAR,
	"process_id" BIGINT,
	"apply_id" BIGINT,
	"proc_inst_id" VARCHAR,
	"task_id" BIGINT,
	"valid_state" TINYINT,
	"create_time" DATETIME,
	"update_time" DATETIME,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	 PRIMARY KEY ("data_id")
);

CREATE TABLE "bpm_form_data" (
	"data_id" BIGINT,
	"data_key" VARCHAR,
	"data_name" VARCHAR,
	"string_value" VARCHAR,
	"boolean_value" TINYINT,
	"number_value" DECIMAL,
	"number_format" VARCHAR,
	"date_value" DATETIME,
	"date_pattern" VARCHAR,
	"select_value" VARCHAR,
	"select_item" VARCHAR,
	"text_value" LONGTEXT,
	"data_type" VARCHAR,
	"form_id" BIGINT,
	"form_key" VARCHAR,
	"tenant_id" VARCHAR,
	"process_id" BIGINT,
	"apply_id" BIGINT,
	"proc_inst_id" VARCHAR,
	"task_id" BIGINT,
	"valid_state" TINYINT,
	"create_time" DATETIME,
	"update_time" DATETIME,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	 PRIMARY KEY ("data_id")
);

CREATE TABLE "bpm_form" (
	"form_id" BIGINT,
	"form_key" VARCHAR,
	"form_name" VARCHAR,
	"tenant_id" VARCHAR,
	"form_type" TINYINT,
	"sort" SMALLINT,
	"form_data" TEXT,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"create_time" DATETIME,
	"update_time" DATETIME,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	 PRIMARY KEY ("form_id")
);

CREATE TABLE "bpm_file_template" (
	"tempalte_id" CHAR,
	"process_id" INT,
	"tenant_id" VARCHAR,
	"file_name" VARCHAR,
	"file_md5_name" VARCHAR,
	"file_extend" VARCHAR,
	"file_path" VARCHAR,
	"file_size" DECIMAL,
	"remarks" VARCHAR,
	"sort" SMALLINT,
	"valid_state" TINYINT,
	"operator_id" INT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("tempalte_id")
);

CREATE TABLE "bpm_file" (
	"file_id" INT,
	"file_instance_code" VARCHAR,
	"file_name" VARCHAR,
	"file_md5_name" VARCHAR,
	"file_path" VARCHAR,
	"file_size" INT,
	"file_extend" VARCHAR,
	"file_status" TINYINT,
	"file_system_code" VARCHAR,
	"file_paltform" VARCHAR,
	"file_service_name" VARCHAR,
	"file_method_name" VARCHAR,
	"file_owner_id" INT,
	"file_owner_name" VARCHAR,
	"tenant_id" VARCHAR,
	"error_message" TEXT,
	"valid_state" TINYINT,
	"operator_id" INT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("file_id")
);

CREATE TABLE "bpm_event" (
	"event_id" INT,
	"event_code" VARCHAR,
	"event_name" VARCHAR,
	"event_type" VARCHAR,
	"process_id" INT,
	"node_id" VARCHAR,
	"request_url" VARCHAR,
	"request_method" VARCHAR,
	"request_headers" TEXT,
	"request_body" TEXT,
	"request_async" TINYINT,
	"response_save" TINYINT,
	"response_var_name" VARCHAR,
	"order_no" INT,
	"tenant_id" VARCHAR,
	"remark" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" INT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("event_id")
);

CREATE TABLE "bpm_dict_item" (
	"item_id" BIGINT,
	"dict_id" BIGINT,
	"item_value" VARCHAR,
	"item_text" VARCHAR,
	"parent_id" BIGINT,
	"tenant_id" VARCHAR,
	"sort" MEDIUMINT,
	"remark" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"update_time" DATETIME,
	"create_time" DATETIME,
	 PRIMARY KEY ("item_id")
);

CREATE TABLE "bpm_dict" (
	"dict_id" BIGINT,
	"dict_code" VARCHAR,
	"dict_name" VARCHAR,
	"dict_tree" TINYINT,
	"tenant_id" VARCHAR,
	"remark" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"update_time" DATETIME,
	"create_time" DATETIME,
	 PRIMARY KEY ("dict_id")
);

CREATE TABLE "bpm_dept" (
	"dept_id" BIGINT,
	"dept_code" VARCHAR,
	"dept_name" VARCHAR,
	"company_id" BIGINT,
	"company_code" VARCHAR,
	"business_line" VARCHAR,
	"tenant_id" VARCHAR,
	"dept_parent_id" BIGINT,
	"dept_parent_code" VARCHAR,
	"dept_level" TINYINT,
	"dept_type" VARCHAR,
	"dept_type_code" VARCHAR,
	"remark" VARCHAR,
	"dept_order" SMALLINT,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("dept_id")
);

CREATE TABLE "bpm_config_template" (
	"template_id" BIGINT,
	"template_code" VARCHAR,
	"template_name" VARCHAR,
	"template_key" VARCHAR,
	"template_value" VARCHAR,
	"template_type" VARCHAR,
	"template_status" TINYINT,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("template_id")
);

CREATE TABLE "bpm_config" (
	"config_id" BIGINT,
	"config_code" VARCHAR,
	"config_name" VARCHAR,
	"template_id" BIGINT,
	"config_key" VARCHAR,
	"config_value" VARCHAR,
	"config_type" VARCHAR,
	"tenant_id" VARCHAR,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("config_id")
);

CREATE TABLE "bpm_company" (
	"company_id" BIGINT,
	"company_code" VARCHAR,
	"company_parent_id" BIGINT,
	"company_parent_code" VARCHAR,
	"company_name" VARCHAR,
	"company_abbr" VARCHAR,
	"company_level" TINYINT,
	"company_order" SMALLINT,
	"company_icon" VARCHAR,
	"company_url" VARCHAR,
	"tenant_id" VARCHAR,
	"company_status" TINYINT,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("company_id")
);

CREATE TABLE "bpm_apply" (
	"apply_id" BIGINT,
	"apply_sn" VARCHAR,
	"proc_inst_id" VARCHAR,
	"apply_title" VARCHAR,
	"apply_user_id" BIGINT,
	"apply_real_name" VARCHAR,
	"apply_dept_id" BIGINT,
	"apply_dept_code" VARCHAR,
	"apply_dept_name" VARCHAR,
	"apply_company_id" BIGINT,
	"apply_company_code" VARCHAR,
	"apply_company_name" VARCHAR,
	"tenant_id" VARCHAR,
	"process_id" BIGINT,
	"process_key" VARCHAR,
	"process_name" VARCHAR,
	"definition_id" VARCHAR,
	"form_key" VARCHAR,
	"system" VARCHAR,
	"platform" VARCHAR,
	"parent_apply_id" BIGINT,
	"apply_status" TINYINT,
	"pre_process_link" VARCHAR,
	"complete_time" DATETIME,
	"remarks" VARCHAR,
	"valid_state" TINYINT,
	"operator_id" BIGINT,
	"operator_name" VARCHAR,
	"create_time" DATETIME,
	"update_time" DATETIME,
	 PRIMARY KEY ("apply_id")
);
