DROP DATABASE IF EXISTS "schema639";
CREATE DATABASE "schema639";
USE "schema639";
CREATE TABLE "vn4_widget" (
	"id" INT,
	"sidebar_id" VARCHAR,
	"theme" VARCHAR,
	"content" TEXT,
	"html" TEXT,
	"created_time" DOUBLE,
	"updated_time" DOUBLE,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP
);

CREATE TABLE "vn4_user" (
	"id" INT,
	"email" VARCHAR,
	"slug" VARCHAR,
	"first_name" VARCHAR,
	"last_name" VARCHAR,
	"password" VARCHAR,
	"role" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"customize_time" VARCHAR,
	"permission" TEXT,
	"remember_token" VARCHAR,
	"type" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "vn4_theme_option" (
	"id" INT,
	"key" VARCHAR,
	"content" TEXT,
	"created_time" DOUBLE,
	"updated_time" DOUBLE,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP
);

CREATE TABLE "vn4_team" (
	"id" INT,
	"title" VARCHAR,
	"position" VARCHAR,
	"image" TEXT,
	"contact" MEDIUMTEXT,
	"type" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "vn4_slug" (
	"id" INT,
	"type" VARCHAR,
	"post_id" INT,
	"slug" VARCHAR,
	"number_update" INT,
	"created_time" DOUBLE,
	"updated_time" DOUBLE,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP
);

CREATE TABLE "vn4_setting" (
	"id" INT,
	"title" VARCHAR,
	"type" VARCHAR,
	"key_word" VARCHAR,
	"author" INT,
	"status" VARCHAR,
	"meta" TEXT,
	"content" TEXT,
	"group" VARCHAR,
	"created_time" DOUBLE,
	"updated_time" DOUBLE,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP
);

CREATE TABLE "vn4_service" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"description" VARCHAR,
	"content" TEXT,
	"image" TEXT,
	"type" VARCHAR,
	"language" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "vn4_project_category" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"description" VARCHAR,
	"type" VARCHAR,
	"language" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "vn4_project" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"description" VARCHAR,
	"content" TEXT,
	"category" VARCHAR,
	"category_detail" TEXT,
	"banner" TEXT,
	"image" TEXT,
	"type" VARCHAR,
	"language" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "vn4_page" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"description" VARCHAR,
	"content" TEXT,
	"content_page" TEXT,
	"type" VARCHAR,
	"language" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "vn4_newsletters" (
	"id" INT,
	"title" VARCHAR,
	"type" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "vn4_menu" (
	"id" INT,
	"title" VARCHAR,
	"type" VARCHAR,
	"status" VARCHAR,
	"theme" VARCHAR,
	"content" TEXT,
	"key_word" VARCHAR,
	"json" TEXT,
	"created_time" DOUBLE,
	"updated_time" DOUBLE,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP
);

CREATE TABLE "vn4_login_time" (
	"id" INT,
	"ip" VARCHAR,
	"count" INT,
	"time" INT,
	"created_time" DOUBLE,
	"updated_time" DOUBLE,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP
);

CREATE TABLE "vn4_jobs" (
	"id" INT,
	"queue" VARCHAR,
	"payload" TEXT,
	"attempts" INT,
	"reserved_at" VARCHAR,
	"created_time" DOUBLE,
	"updated_time" DOUBLE,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP
);

CREATE TABLE "vn4_ecommerce_product_variable_ecommerce_product_attribute_value" (
	"id" INT,
	"post_id" INT,
	"tag_id" INT,
	"field" VARCHAR,
	"type" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP
);

CREATE TABLE "vn4_ecommerce_product_ecommerce_tag" (
	"id" INT,
	"post_id" INT,
	"tag_id" INT,
	"field" VARCHAR,
	"type" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP
);

CREATE TABLE "vn4_contact" (
	"id" INT,
	"title" VARCHAR,
	"email" VARCHAR,
	"subject" VARCHAR,
	"message" TEXT,
	"type" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "vn4_blog_post_blog_tag" (
	"id" INT,
	"post_id" INT,
	"tag_id" INT,
	"field" VARCHAR,
	"type" VARCHAR
);

CREATE TABLE "ecommerce_tag" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"description" VARCHAR,
	"type" VARCHAR,
	"count_ecommerce_product_ecommerce_tag" INT,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "ecommerce_product_variable" (
	"id" INT,
	"title" VARCHAR,
	"description" VARCHAR,
	"price" VARCHAR,
	"sale_price" VARCHAR,
	"thumbnail" TEXT,
	"images" TEXT,
	"weight" VARCHAR,
	"length" VARCHAR,
	"width" VARCHAR,
	"height" VARCHAR,
	"check_list" VARCHAR,
	"stock_status" VARCHAR,
	"shipping" VARCHAR,
	"download_file" MEDIUMTEXT,
	"download_limit" VARCHAR,
	"download_expiry" VARCHAR,
	"ecommerce_product" VARCHAR,
	"ecommerce_product_detail" TEXT,
	"attribute_value" TEXT,
	"type" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "ecommerce_product_attribute_value" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"description" VARCHAR,
	"ecommerce_product_attribute" VARCHAR,
	"content" VARCHAR,
	"ecommerce_product_attribute_detail" TEXT,
	"type" VARCHAR,
	"count_ecommerce_product_variable_attribute_value" INT,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "ecommerce_product_attribute" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"description" VARCHAR,
	"type" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "ecommerce_product" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"product_type" VARCHAR,
	"price" VARCHAR,
	"sale_price" VARCHAR,
	"ecommerce_category" VARCHAR,
	"ecommerce_category_detail" TEXT,
	"ecommerce_tag" TEXT,
	"thumbnail" TEXT,
	"images" TEXT,
	"type" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "ecommerce_category" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"parent" VARCHAR,
	"parent_detail" TEXT,
	"description" VARCHAR,
	"type" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "blog_tag" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"description" VARCHAR,
	"type" VARCHAR,
	"language" VARCHAR,
	"count_blog_post_tag" INT,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "blog_post" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"description" VARCHAR,
	"content" TEXT,
	"category" VARCHAR,
	"category_detail" TEXT,
	"tag" TEXT,
	"image" TEXT,
	"type" VARCHAR,
	"language" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "blog_category" (
	"id" INT,
	"title" VARCHAR,
	"slug" VARCHAR,
	"parent" VARCHAR,
	"parent_detail" TEXT,
	"description" VARCHAR,
	"type" VARCHAR,
	"language" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);

CREATE TABLE "ace_custom_fields" (
	"id" INT,
	"title" VARCHAR,
	"location" TEXT,
	"fields" TEXT,
	"number_field" VARCHAR,
	"related" VARCHAR,
	"type" VARCHAR,
	"meta" MEDIUMTEXT,
	"author" INT,
	"template" VARCHAR,
	"order" INT,
	"status" VARCHAR,
	"status_old" VARCHAR,
	"password" VARCHAR,
	"post_date_gmt" INT,
	"visibility" VARCHAR,
	"is_homepage" VARCHAR,
	"ip" VARCHAR,
	"created_at" TIMESTAMP,
	"updated_at" TIMESTAMP,
	"created_time" DOUBLE,
	"updated_time" DOUBLE
);
