DROP DATABASE IF EXISTS "schema2008";
CREATE DATABASE "schema2008";
USE "schema2008";
CREATE TABLE "vw_filesearch" (
	"agency" TEXT,
	"entity_number" TEXT,
	"type" TEXT,
	"programs" TEXT,
	"name" TEXT,
	"title" TEXT,
	"addresses" TEXT,
	"federal_register_notice" TEXT,
	"start_date" TEXT,
	"end_date" TEXT,
	"standard_order" TEXT,
	"license_requirement" TEXT,
	"license_policy" TEXT,
	"call_sign" TEXT,
	"vessel_type" TEXT,
	"gross_tonnage" TEXT,
	"gross_registered_tonnage" TEXT,
	"vessel_flag" TEXT,
	"vessel_owner" TEXT,
	"remarks" TEXT,
	"source_list_url" TEXT,
	"alt_names" TEXT,
	"citizenships" TEXT,
	"dates_of_birth" TEXT,
	"nationalities" TEXT,
	"places_of_birth" TEXT,
	"source_information_url" TEXT,
	"country" VARCHAR,
	"user_id" VARCHAR
);

CREATE TABLE "vw_countries" (
	"uid" INT,
	"agency" TEXT,
	"entity_number" TEXT,
	"type" TEXT,
	"programs" TEXT,
	"name" TEXT,
	"title" TEXT,
	"addresses" TEXT,
	"federal_register_notice" TEXT,
	"start_date" TEXT,
	"end_date" TEXT,
	"standard_order" TEXT,
	"license_requirement" TEXT,
	"license_policy" TEXT,
	"call_sign" TEXT,
	"vessel_type" TEXT,
	"gross_tonnage" TEXT,
	"gross_registered_tonnage" TEXT,
	"vessel_flag" TEXT,
	"vessel_owner" TEXT,
	"remarks" TEXT,
	"source_list_url" TEXT,
	"alt_names" TEXT,
	"citizenships" TEXT,
	"dates_of_birth" TEXT,
	"nationalities" TEXT,
	"places_of_birth" TEXT,
	"source_information_url" TEXT,
	"country" VARCHAR
);

CREATE TABLE "user" (
	"id" INT,
	"username" VARCHAR,
	"first_name" VARCHAR,
	"middle_name" VARCHAR,
	"last_name" VARCHAR,
	"auth_key" VARCHAR,
	"password_hash" VARCHAR,
	"password_reset_token" VARCHAR,
	"email" VARCHAR,
	"status" SMALLINT,
	"created_at" INT,
	"updated_at" INT,
	"verification_token" VARCHAR,
	"user_role" VARCHAR
);

CREATE TABLE "usa" (
	"uid" INT,
	"agency" VARCHAR,
	"entity_number" VARCHAR,
	"type" VARCHAR,
	"programs" VARCHAR,
	"name" VARCHAR,
	"title" VARCHAR,
	"addresses" VARCHAR,
	"federal_register_notice" VARCHAR,
	"start_date" VARCHAR,
	"end_date" VARCHAR,
	"standard_order" VARCHAR,
	"license_requirement" VARCHAR,
	"license_policy" VARCHAR,
	"call_sign" VARCHAR,
	"vessel_type" VARCHAR,
	"gross_tonnage" VARCHAR,
	"gross_registered_tonnage" VARCHAR,
	"vessel_flag" VARCHAR,
	"vessel_owner" VARCHAR,
	"remarks" VARCHAR,
	"source_list_url" VARCHAR,
	"alt_names" VARCHAR,
	"citizenships" VARCHAR,
	"dates_of_birth" VARCHAR,
	"nationalities" VARCHAR,
	"places_of_birth" VARCHAR,
	"source_information_url" VARCHAR,
	"country" VARCHAR
);

CREATE TABLE "uk" (
	"uid" INT,
	"agency" VARCHAR,
	"entity_number" VARCHAR,
	"type" VARCHAR,
	"programs" VARCHAR,
	"name" VARCHAR,
	"title" VARCHAR,
	"addresses" VARCHAR,
	"federal_register_notice" VARCHAR,
	"start_date" VARCHAR,
	"end_date" VARCHAR,
	"standard_order" VARCHAR,
	"license_requirement" VARCHAR,
	"license_policy" VARCHAR,
	"call_sign" VARCHAR,
	"vessel_type" VARCHAR,
	"gross_tonnage" VARCHAR,
	"gross_registered_tonnage" VARCHAR,
	"vessel_flag" VARCHAR,
	"vessel_owner" VARCHAR,
	"remarks" VARCHAR,
	"source_list_url" VARCHAR,
	"alt_names" VARCHAR,
	"citizenships" VARCHAR,
	"dates_of_birth" VARCHAR,
	"nationalities" VARCHAR,
	"places_of_birth" VARCHAR,
	"source_information_url" VARCHAR,
	"country" VARCHAR
);

CREATE TABLE "migration" (
	"version" VARCHAR,
	"apply_time" INT
);

CREATE TABLE "japan" (
	"uid" INT,
	"agency" VARCHAR,
	"entity_number" VARCHAR,
	"type" VARCHAR,
	"programs" VARCHAR,
	"name" VARCHAR,
	"title" VARCHAR,
	"addresses" VARCHAR,
	"federal_register_notice" VARCHAR,
	"start_date" VARCHAR,
	"end_date" VARCHAR,
	"standard_order" VARCHAR,
	"license_requirement" VARCHAR,
	"license_policy" VARCHAR,
	"call_sign" VARCHAR,
	"vessel_type" VARCHAR,
	"gross_tonnage" VARCHAR,
	"gross_registered_tonnage" VARCHAR,
	"vessel_flag" VARCHAR,
	"vessel_owner" VARCHAR,
	"remarks" VARCHAR,
	"source_list_url" VARCHAR,
	"alt_names" VARCHAR,
	"citizenships" VARCHAR,
	"dates_of_birth" VARCHAR,
	"nationalities" VARCHAR,
	"places_of_birth" VARCHAR,
	"source_information_url" VARCHAR,
	"country" VARCHAR
);

CREATE TABLE "file_search" (
	"search_id" INT,
	"name" TINYTEXT,
	"alias_name" TINYTEXT,
	"passport_details" TINYTEXT,
	"nationalities" TINYTEXT,
	"citizenships" TINYTEXT,
	"entity_number" TINYTEXT,
	"user_id" VARCHAR
);

CREATE TABLE "eu" (
	"uid" INT,
	"agency" VARCHAR,
	"entity_number" VARCHAR,
	"type" VARCHAR,
	"programs" VARCHAR,
	"name" VARCHAR,
	"title" VARCHAR,
	"addresses" VARCHAR,
	"federal_register_notice" VARCHAR,
	"start_date" VARCHAR,
	"end_date" VARCHAR,
	"standard_order" VARCHAR,
	"license_requirement" VARCHAR,
	"license_policy" VARCHAR,
	"call_sign" VARCHAR,
	"vessel_type" VARCHAR,
	"gross_tonnage" VARCHAR,
	"gross_registered_tonnage" VARCHAR,
	"vessel_flag" VARCHAR,
	"vessel_owner" VARCHAR,
	"remarks" VARCHAR,
	"source_list_url" VARCHAR,
	"alt_names" VARCHAR,
	"citizenships" VARCHAR,
	"dates_of_birth" VARCHAR,
	"nationalities" VARCHAR,
	"places_of_birth" VARCHAR,
	"source_information_url" VARCHAR,
	"country" VARCHAR
);

CREATE TABLE "china" (
	"uid" INT,
	"agency" VARCHAR,
	"entity_number" VARCHAR,
	"type" VARCHAR,
	"programs" VARCHAR,
	"name" VARCHAR,
	"title" VARCHAR,
	"addresses" VARCHAR,
	"federal_register_notice" VARCHAR,
	"start_date" VARCHAR,
	"end_date" VARCHAR,
	"standard_order" VARCHAR,
	"license_requirement" VARCHAR,
	"license_policy" VARCHAR,
	"call_sign" VARCHAR,
	"vessel_type" VARCHAR,
	"gross_tonnage" VARCHAR,
	"gross_registered_tonnage" VARCHAR,
	"vessel_flag" VARCHAR,
	"vessel_owner" VARCHAR,
	"remarks" VARCHAR,
	"source_list_url" VARCHAR,
	"alt_names" VARCHAR,
	"citizenships" VARCHAR,
	"dates_of_birth" VARCHAR,
	"nationalities" VARCHAR,
	"places_of_birth" VARCHAR,
	"source_information_url" VARCHAR,
	"country" VARCHAR
);

CREATE TABLE "canada" (
	"uid" INT,
	"agency" VARCHAR,
	"entity_number" VARCHAR,
	"type" VARCHAR,
	"programs" VARCHAR,
	"name" VARCHAR,
	"title" VARCHAR,
	"addresses" VARCHAR,
	"federal_register_notice" VARCHAR,
	"start_date" VARCHAR,
	"end_date" VARCHAR,
	"standard_order" VARCHAR,
	"license_requirement" VARCHAR,
	"license_policy" VARCHAR,
	"call_sign" VARCHAR,
	"vessel_type" VARCHAR,
	"gross_tonnage" VARCHAR,
	"gross_registered_tonnage" VARCHAR,
	"vessel_flag" VARCHAR,
	"vessel_owner" VARCHAR,
	"remarks" VARCHAR,
	"source_list_url" VARCHAR,
	"alt_names" VARCHAR,
	"citizenships" VARCHAR,
	"dates_of_birth" VARCHAR,
	"nationalities" VARCHAR,
	"places_of_birth" VARCHAR,
	"source_information_url" VARCHAR,
	"country" VARCHAR
);

CREATE TABLE "australia" (
	"uid" INT,
	"agency" VARCHAR,
	"entity_number" VARCHAR,
	"type" VARCHAR,
	"programs" VARCHAR,
	"name" VARCHAR,
	"title" VARCHAR,
	"addresses" VARCHAR,
	"federal_register_notice" VARCHAR,
	"start_date" VARCHAR,
	"end_date" VARCHAR,
	"standard_order" VARCHAR,
	"license_requirement" VARCHAR,
	"license_policy" VARCHAR,
	"call_sign" VARCHAR,
	"vessel_type" VARCHAR,
	"gross_tonnage" VARCHAR,
	"gross_registered_tonnage" VARCHAR,
	"vessel_flag" VARCHAR,
	"vessel_owner" VARCHAR,
	"remarks" VARCHAR,
	"source_list_url" VARCHAR,
	"alt_names" VARCHAR,
	"citizenships" VARCHAR,
	"dates_of_birth" VARCHAR,
	"nationalities" VARCHAR,
	"places_of_birth" VARCHAR,
	"source_information_url" VARCHAR,
	"country" VARCHAR
);
