DROP DATABASE IF EXISTS "schema409";
CREATE DATABASE "schema409";
USE "schema409";
CREATE TABLE "table}`" (
	"id" INT,
	"id" INT,
	"id" INT,
	"id" INT,
	"id" INT,
	"id" INT,
	"paymenttype" VARCHAR,
	"image" VARCHAR,
	"height" INT,
	"position" INT,
	"displaytype" VARCHAR,
	"integration" VARCHAR,
	"paymentnumber" INT,
	"firstpaymentpart" INT,
	"orderrepeated" INT,
	"discount" INT,
	"minamount" DECIMAL,
	"maxamount" DECIMAL,
	"filtered_category_mode" VARCHAR,
	"filtered_category_primaries" TEXT,
	"paymentmode" VARCHAR,
	"paymentreport" VARCHAR,
	"id_shop" INT,
	"id_shop" INT,
	"pid" VARCHAR,
	"pid" VARCHAR,
	"pid" VARCHAR,
	"id_order" INT,
	"id_order" INT,
	"state" VARCHAR,
	"state" VARCHAR,
	"mode" VARCHAR,
	"mode" VARCHAR,
	"amount" INT,
	"amount" INT,
	"created_at" DATETIME,
	"created_at" DATETIME,
	"created_at" DATETIME,
	"state_order_before" VARCHAR,
	"state_order_after" VARCHAR,
	"rank" INT,
	"session" VARCHAR,
	"browser" VARCHAR,
	"device" VARCHAR,
	"pages" INT,
	"pictures" INT,
	"time" INT,
	"locked_at" INT,
	"id_category" INT,
	"payment" VARCHAR,
	 PRIMARY KEY ("id")
);
