DROP DATABASE IF EXISTS "schema2498";
CREATE DATABASE "schema2498";
USE "schema2498";
CREATE TABLE "schema_migrations" (
	"version" CHARACTER VARYING,
	 PRIMARY KEY ("version")
);

CREATE TABLE "products" (
	"id" TEXT,
	"object" TEXT,
	"active" BOOLEAN,
	"description" TEXT,
	"metadata" LONGTEXT,
	"name" TEXT,
	"created" INTEGER,
	"images" LONGTEXT,
	"livemode" BOOLEAN,
	"package_dimensions" LONGTEXT,
	"shippable" BOOLEAN,
	"statement_descriptor" TEXT,
	"unit_label" TEXT,
	"updated" INTEGER,
	"url" TEXT,
	 PRIMARY KEY ("id")
);

CREATE TABLE "prices" (
	"id" TEXT,
	"object" TEXT,
	"active" BOOLEAN,
	"currency" TEXT,
	"metadata" LONGTEXT,
	"nickname" TEXT,
	"recurring" LONGTEXT,
	"type" ENUM,
	"unit_amount" INTEGER,
	"billing_scheme" TEXT,
	"created" INTEGER,
	"livemode" BOOLEAN,
	"lookup_key" TEXT,
	"tiers_mode" ENUM,
	"transform_quantity" LONGTEXT,
	"unit_amount_decimal" TEXT,
	"product" TEXT,
	 PRIMARY KEY ("id"),
	 CONSTRAINT "prices_product_fkey" FOREIGN KEY ("product") REFERENCES "products" ("id")
);

CREATE TABLE "plans" (
	"id" TEXT,
	"object" TEXT,
	"name" TEXT,
	"tiers" LONGTEXT,
	"active" BOOLEAN,
	"amount" BIGINT,
	"created" INTEGER,
	"product" TEXT,
	"updated" INTEGER,
	"currency" TEXT,
	"interval" TEXT,
	"livemode" BOOLEAN,
	"metadata" LONGTEXT,
	"nickname" TEXT,
	"tiers_mode" TEXT,
	"usage_type" TEXT,
	"billing_scheme" TEXT,
	"interval_count" BIGINT,
	"aggregate_usage" TEXT,
	"transform_usage" TEXT,
	"trial_period_days" BIGINT,
	"statement_descriptor" TEXT,
	"statement_description" TEXT,
	 PRIMARY KEY ("id")
);

CREATE TABLE "payouts" (
	"id" TEXT,
	"object" TEXT,
	"date" TEXT,
	"type" TEXT,
	"amount" BIGINT,
	"method" TEXT,
	"status" TEXT,
	"created" INTEGER,
	"updated" INTEGER,
	"currency" TEXT,
	"livemode" BOOLEAN,
	"metadata" LONGTEXT,
	"automatic" BOOLEAN,
	"recipient" TEXT,
	"description" TEXT,
	"destination" TEXT,
	"source_type" TEXT,
	"arrival_date" TEXT,
	"bank_account" LONGTEXT,
	"failure_code" TEXT,
	"transfer_group" TEXT,
	"amount_reversed" BIGINT,
	"failure_message" TEXT,
	"source_transaction" TEXT,
	"balance_transaction" TEXT,
	"statement_descriptor" TEXT,
	"statement_description" TEXT,
	"failure_balance_transaction" TEXT,
	 PRIMARY KEY ("id")
);

CREATE TABLE "events" (
	"id" TEXT,
	"object" TEXT,
	"data" LONGTEXT,
	"type" TEXT,
	"created" INTEGER,
	"request" TEXT,
	"updated" INTEGER,
	"livemode" BOOLEAN,
	"api_version" TEXT,
	"pending_webhooks" BIGINT,
	 PRIMARY KEY ("id")
);

CREATE TABLE "disputes" (
	"id" TEXT,
	"object" TEXT,
	"amount" BIGINT,
	"charge" TEXT,
	"reason" TEXT,
	"status" TEXT,
	"created" INTEGER,
	"updated" INTEGER,
	"currency" TEXT,
	"evidence" LONGTEXT,
	"livemode" BOOLEAN,
	"metadata" LONGTEXT,
	"evidence_details" LONGTEXT,
	"balance_transactions" LONGTEXT,
	"is_charge_refundable" BOOLEAN,
	 PRIMARY KEY ("id")
);

CREATE TABLE "customers" (
	"id" TEXT,
	"object" TEXT,
	"address" LONGTEXT,
	"description" TEXT,
	"email" TEXT,
	"metadata" LONGTEXT,
	"name" TEXT,
	"phone" TEXT,
	"shipping" LONGTEXT,
	"balance" INTEGER,
	"created" INTEGER,
	"currency" TEXT,
	"default_source" TEXT,
	"delinquent" BOOLEAN,
	"discount" LONGTEXT,
	"invoice_prefix" TEXT,
	"invoice_settings" LONGTEXT,
	"livemode" BOOLEAN,
	"next_invoice_sequence" INTEGER,
	"preferred_locales" LONGTEXT,
	"tax_exempt" TEXT,
	 PRIMARY KEY ("id")
);

CREATE TABLE "subscriptions" (
	"id" TEXT,
	"object" TEXT,
	"cancel_at_period_end" BOOLEAN,
	"current_period_end" INTEGER,
	"current_period_start" INTEGER,
	"default_payment_method" TEXT,
	"items" LONGTEXT,
	"metadata" LONGTEXT,
	"pending_setup_intent" TEXT,
	"pending_update" LONGTEXT,
	"status" ENUM,
	"application_fee_percent" DOUBLE PRECISION,
	"billing_cycle_anchor" INTEGER,
	"billing_thresholds" LONGTEXT,
	"cancel_at" INTEGER,
	"canceled_at" INTEGER,
	"collection_method" TEXT,
	"created" INTEGER,
	"days_until_due" INTEGER,
	"default_source" TEXT,
	"default_tax_rates" LONGTEXT,
	"discount" LONGTEXT,
	"ended_at" INTEGER,
	"livemode" BOOLEAN,
	"next_pending_invoice_item_invoice" INTEGER,
	"pause_collection" LONGTEXT,
	"pending_invoice_item_interval" LONGTEXT,
	"start_date" INTEGER,
	"transfer_data" LONGTEXT,
	"trial_end" LONGTEXT,
	"trial_start" LONGTEXT,
	"schedule" TEXT,
	"customer" TEXT,
	"latest_invoice" TEXT,
	"plan" TEXT,
	 PRIMARY KEY ("id"),
	 CONSTRAINT "subscriptions_customer_fkey" FOREIGN KEY ("customer") REFERENCES "customers" ("id")
);

CREATE TABLE "invoices" (
	"id" TEXT,
	"object" TEXT,
	"auto_advance" BOOLEAN,
	"collection_method" TEXT,
	"currency" TEXT,
	"description" TEXT,
	"hosted_invoice_url" TEXT,
	"lines" LONGTEXT,
	"metadata" LONGTEXT,
	"period_end" INTEGER,
	"period_start" INTEGER,
	"status" ENUM,
	"total" BIGINT,
	"account_country" TEXT,
	"account_name" TEXT,
	"account_tax_ids" LONGTEXT,
	"amount_due" BIGINT,
	"amount_paid" BIGINT,
	"amount_remaining" BIGINT,
	"application_fee_amount" BIGINT,
	"attempt_count" INTEGER,
	"attempted" BOOLEAN,
	"billing_reason" TEXT,
	"created" INTEGER,
	"custom_fields" LONGTEXT,
	"customer_address" LONGTEXT,
	"customer_email" TEXT,
	"customer_name" TEXT,
	"customer_phone" TEXT,
	"customer_shipping" LONGTEXT,
	"customer_tax_exempt" TEXT,
	"customer_tax_ids" LONGTEXT,
	"default_tax_rates" LONGTEXT,
	"discount" LONGTEXT,
	"discounts" LONGTEXT,
	"due_date" INTEGER,
	"ending_balance" INTEGER,
	"footer" TEXT,
	"invoice_pdf" TEXT,
	"last_finalization_error" LONGTEXT,
	"livemode" BOOLEAN,
	"next_payment_attempt" INTEGER,
	"number" TEXT,
	"paid" BOOLEAN,
	"payment_settings" LONGTEXT,
	"post_payment_credit_notes_amount" INTEGER,
	"pre_payment_credit_notes_amount" INTEGER,
	"receipt_number" TEXT,
	"starting_balance" INTEGER,
	"statement_descriptor" TEXT,
	"status_transitions" LONGTEXT,
	"subscription_proration_date" INTEGER,
	"subtotal" INTEGER,
	"tax" INTEGER,
	"threshold_reason" LONGTEXT,
	"total_discount_amounts" LONGTEXT,
	"total_tax_amounts" LONGTEXT,
	"transfer_data" LONGTEXT,
	"webhooks_delivered_at" INTEGER,
	"customer" TEXT,
	"subscription" TEXT,
	"payment_intent" TEXT,
	"default_payment_method" TEXT,
	"default_source" TEXT,
	"on_behalf_of" TEXT,
	"charge" TEXT,
	 PRIMARY KEY ("id"),
	 CONSTRAINT "invoices_subscription_fkey" FOREIGN KEY ("subscription") REFERENCES "subscriptions" ("id"),
	 CONSTRAINT "invoices_customer_fkey" FOREIGN KEY ("customer") REFERENCES "customers" ("id")
);

CREATE TABLE "coupons" (
	"id" TEXT,
	"object" TEXT,
	"name" TEXT,
	"valid" BOOLEAN,
	"created" INTEGER,
	"updated" INTEGER,
	"currency" TEXT,
	"duration" TEXT,
	"livemode" BOOLEAN,
	"metadata" LONGTEXT,
	"redeem_by" INTEGER,
	"amount_off" BIGINT,
	"percent_off" DOUBLE PRECISION,
	"times_redeemed" BIGINT,
	"max_redemptions" BIGINT,
	"duration_in_months" BIGINT,
	"percent_off_precise" DOUBLE PRECISION,
	 PRIMARY KEY ("id")
);

CREATE TABLE "charges" (
	"id" TEXT,
	"object" TEXT,
	"card" LONGTEXT,
	"paid" BOOLEAN,
	"order" TEXT,
	"amount" BIGINT,
	"review" TEXT,
	"source" LONGTEXT,
	"status" TEXT,
	"created" INTEGER,
	"dispute" TEXT,
	"invoice" TEXT,
	"outcome" LONGTEXT,
	"refunds" LONGTEXT,
	"updated" INTEGER,
	"captured" BOOLEAN,
	"currency" TEXT,
	"customer" TEXT,
	"livemode" BOOLEAN,
	"metadata" LONGTEXT,
	"refunded" BOOLEAN,
	"shipping" LONGTEXT,
	"application" TEXT,
	"description" TEXT,
	"destination" TEXT,
	"failure_code" TEXT,
	"on_behalf_of" TEXT,
	"fraud_details" LONGTEXT,
	"receipt_email" TEXT,
	"payment_intent" TEXT,
	"receipt_number" TEXT,
	"transfer_group" TEXT,
	"amount_refunded" BIGINT,
	"application_fee" TEXT,
	"failure_message" TEXT,
	"source_transfer" TEXT,
	"balance_transaction" TEXT,
	"statement_descriptor" TEXT,
	"statement_description" TEXT,
	"payment_method_details" LONGTEXT,
	 PRIMARY KEY ("id")
);
